### PR TITLE
Replace arm based source image with arm32v7/node

### PR DESCRIPTION
**Pull request by bastilimbach**

### CODE REVIEW

**Comment by MaxAtoms** [comment]
The `node` image can now be used by the Raspberry Pi as well, if I am not mistaken:

> As of 2017-09-12, these other architectures are included under the non-prefixed images via "manifest lists" (also known as "indexes" in the OCI image specification), such that, for example, docker run hello-world should run as-is on all supported platforms.
Source: [Docker Official Images](https://github.com/docker-library/official-images#architectures-other-than-amd64)

If that is correct, I suggest simply removing the separate `Raspberry` directory so that there is only one Dockerfile for all platforms.

**Comment by blake** [comment]
FWIW, these built without issue in blake/docker-MagicMirror@beaf5ff8.

I also agree with @MaxAtoms, best to simplify by using one Dockerfile.

**Comment by bastilimbach** [comment]
@MaxAtoms oh thank you. This is awesome! I‘ll remove the separate image 👍

**Comment by khassel** [comment]
> The `node` image can now be used by the Raspberry Pi as well, if I am not mistaken:

thats interesting. But after some testing this seems only to be a sort of switch.

E.g. if you `docker pull node:slim` on os `"Architecture": "amd64"` you will get `image id=4484643658ed`, on os `"Architecture": "arm"` you will get `image id=57af354b4496`.

So the name `node:slim` is identical, but the content of the 2 images is os specific. So if you transfer the `amd64` image on a raspberry, you can't use this image, you will get the (expected) error `standard_init_linux.go:211: exec user process caused "exec format error"`.

**Comment by bastilimbach** [comment]
@khassel, @blake, @MaxAtoms Ok so if I'm understanding this correctly, the base image `node` has images for multiple architectures like amd64 & arm, etc. These architectures are all "collected" under one main docker image called "node". This is possible due to the new [docker manifests](https://docs.docker.com/engine/reference/commandline/manifest/) for building multi-arch images, right?

Now if I want to do the same, I only need one Dockerfile which uses `node` as the base image, push two tags (e.g `:arm` & `:amd64`)  and create a manifest for it to "bundle" the two architectures under one `:latest` tag using: 

```bash
$ docker manifest create bastilimbach/docker-MagicMirror:latest bastilimbach/docker-MagicMirror:arm bastilimbach/docker-MagicMirror:amd64
$ docker manifest annotate --arch arm bastilimbach/docker-MagicMirror bastilimbach/docker-MagicMirror:arm
$ docker manifest push bastilimbach/docker-MagicMirror
```

Has anybody of you some experience with that and could maybe help?

Reference: [https://billglover.me/2018/10/30/multi-architecture-docker-builds/](https://billglover.me/2018/10/30/multi-architecture-docker-builds/)

**Comment by bastilimbach** [comment]
Ping @idoodler. Do you have any experience with this topic perhaps?

**Comment by idoodler** [comment]
>Ping @idoodler. Do you have any experience with this topic perhaps?

@bastilimbach No, I just recently started with Docker.

**Pull request closed without merging**
