### PR TITLE
Fix image build & provide multi-arch image

### LINKED ISSUE #13: Module directory checking and updating
After seeing a update message, I thought about updating my container and checked your repo first to see if it handled updating the default modules.
Looking at this script, you are checking if `/opt/magic_mirror/modules` is a **regular** file, not a directory
https://github.com/bastilimbach/docker-MagicMirror/blob/0d92ce00bbf014606ebf784bdf77a52c5124ef62/docker-entrypoint.sh#L3
This means every time the entry script is invoked it will copy over everything from `/opt/default_modules/`. This also does not account for files that are not present anymore in the defaults

I forked your repo to see if I could come up with a way of solving the issue, so far i have changed the check to see if the `/opt/magic_mirror/modules/default` folder exists and move all my modules in a sub folder, but that makes adding modules also more complicated, requiring the subdir in the name or compiling a js file that defines all modules like the default folder has (this would involve making a script to compile this file each boot).

Another idea was to store and check for a version file in the module directory to see if it needs updating.

What do you think would be a good idea to go about solving this?

### LINKED ISSUE #19: Docker mm update
Hi 

I have just installed mm using your docker image which is supposed to be the latest one as I checked in the docker hub that your files were updated 2 days ago.

However I get a message regarding updating my mm. I thought I had the latest one released 2 days ago i.e. 2.7.1. Can you please help ? I have already deleted the image on portainer and pulled the latest one but still no joy.

Also how do I check my mm version ? Do I have to login into mm container ? If yes what is the username ?

Thank you again.

### PR DESCRIPTION
**Pull request by bastilimbach**
Closes #21 
Closes #19 
Closes #13 

ToDo:
- [X] Create workflow for GitHub action (Replaces Travis CI) **Will use Travis for now as the docker implementation for GitHub actions is kind of bad.**
- [x] Create manifest for multi-arch docker image

### CODE REVIEW

**Comment by Legion2** [comment]
@bastilimbach what was the problem with GitHub Actions? Why didn't you used it in the end?

**Comment by bastilimbach** [comment]
@Legion2 “Will use Travis for now as the docker implementation for GitHub actions is kind of bad.“ This was before the new GitHub Actions. I tried to switch as this was in beta. 

I might consider moving to the new GitHub actions now. They look really promising and so much easier with the new yaml syntax. 

I‘m just not internally sure if I can schedule them using cron 🤔

**Comment by Legion2** [comment]
you can schedule GitHub Actions with cron

**Comment by bastilimbach** [comment]
Then maybe I should take another look at GitHub actions!

**Comment by bastilimbach** [comment]
@Legion2 I created issue #43. Are you familiar with the GitHub actions syntax? Maybe you could help here :)

**Comment by Legion2** [comment]
Yes I already have created many GitHub Actions workflows and also migrated some from Travis. I can provide a PR if you want maybe next week.

**Pull request merged**
