### PR TITLE
Raspberry pi image fix

### LINKED ISSUE #1: Build for raspberry pi image is failing
Hi, 
there are only 2 versions in docker store, latest and alpine. raspberry is missing.
Thanks,
Karsten.

### PR DESCRIPTION
**Pull request by bastilimbach**
This is an attempt to fix the raspberry (arm) version of the docker hub image.
Fixes #1

### CODE REVIEW

**Comment by bastilimbach** [comment]
@khassel I used the same base image as your Dockerfile and [it is still failing](https://hub.docker.com/r/bastilimbach/docker-magicmirror/builds/). Do you have any more ideas?

**Comment by khassel** [comment]
Looked into your build.
Error: exec user process caused "exec format error"
Your Setup is "Arch: amd64". Think it should be "ARM" or similar.

**Comment by khassel** [comment]
Found nothing to change "Arch" in docker cloud build ...
You can build the image locally and use docker command-line, steps:
a) docker tag
b) docker login
c) docker push

**Comment by bastilimbach** [comment]
Yeah as mentioned [here](https://forums.docker.com/t/automated-build-raspberry-pi-based-image-on-docker-hub/4155) the automatic build always uses an x86_64 architecture. I'm thinking about building and pushing the arm image using [Travis CIs Docker service](https://docs.travis-ci.com/user/docker/). I don't know if this will work but I'll give this a go and we'll see.

**Comment by bastilimbach** [comment]
"[Setup a simple CI pipeline to build Docker images for ARM](https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/)" looks interesting. Will take a look at that.

**Comment by khassel** [comment]
works! Test with my setup: https://travis-ci.org/khassel/docker-mm/builds/226988256

Tested only the server-only version, test on raspi tomorrow ...

**Comment by bastilimbach** [comment]
Awesome! Thank's @khassel. Do you want to open a PR for that or should I implement this here?

**Comment by khassel** [comment]
not yet ...
please first take a look into my repo: https://github.com/khassel/docker-mm
The idea is to publish only one image but to start it in different ways (serveronly and raspberry), see sub-directories.
I'm waiting for new pi-hardware to test this (hopefully tomorrow). There are still problems getting "npm start" working and connecting the container to the pi display.

**Comment by bastilimbach** [comment]
Two types (serveronly and raspberry) would be great, but is it possible to start electron from a docker container on a raspberry? I'm not at home over the weekend, but when I'm back I can test this on a Raspberry Pi 3

**Comment by bastilimbach** [comment]
Is there a specific reason, why you used a compose file instead of a normal Dockerfile in the subfolders?

**Comment by khassel** [comment]
electron is the problem Nr.1, getting the display from the container Nr.2.
You don't need docker-compose, but it's handy. Otherwise you have to type "docker run" with a very long command-line und you have to save this command-line somewhere. With docker-compose you do only "docker-compose up -d" in the yml-directory.

**Comment by khassel** [comment]
The trick is to override the entrypoint in "\up-raspberry\docker-compose.yml".

**Comment by khassel** [comment]
Updated https://github.com/khassel/docker-mm and basic things are working now.

**Comment by bastilimbach** [comment]
So I finally found the time to look into this. Could you please look in your #5 PR? I commented on some lines. In my opinion, the Travis integration to build the raspberry image is excellent, but I have some concerns with the implementation of Magic Mirror UI with Docker. (More described in the line comments)

**Comment by bastilimbach** [comment]
@khassel What do you think about creating a section in the README which points to your fork? Closing this for now. 👍

**Comment by khassel** [comment]
yes, had this idea too 👍 but would prefer to link to my stuff at https://github.com/khassel/docker-mm

**Pull request closed without merging**
